@startuml
start
if (Застосунок запускається?) then (так)
  :Отримати JSON зі сховища;
  :Десеріалізувати список;
  :Оновити масиви завдань;
endif
if (Зміни у списку завдань?) then (так)
  :Серіалізувати список у JSON;
  :Зберегти у shared_preferences;
endif
stop
@enduml